### ISSUE TITLE
Does not lauch on aarch64: libjsoncpp.so.24 missing

### ISSUE THREAD

**Issue by 1peter10** [flathub/com.gitlab.j0chn.nextcloud_password_client#1]
Hi,

I tried to run the app on my Purism Librem 5 (PureOS Byzantium == Debian Bullseye), but it does not start.
When starting it manually

`$ flatpak run com.gitlab.j0chn.nextcloud_password_client`

it fails with the following error:

`nextcloud_password_client: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory`

**Comment by hfiguiere** [comment]
The aarch64 binary seem to expect something different than 
```
lrwxrwxrwx 1 hub hub      15 Apr  9 12:34 libjsoncpp.so -> libjsoncpp.so.1
lrwxrwxrwx 1 hub hub      19 Apr  9 12:34 libjsoncpp.so.1 -> libjsoncpp.so.1.7.6
-rwxr-xr-x 2 hub hub  231408 Dec 31  1969 libjsoncpp.so.1.7.6
```
as per ldd

While the x86_64 binary doesn't even seem to require it (but one of the .so do).

**Comment by j0chn1** [comment]
Got the same on my raspberry on which the app was built. Any ideas on how to solve it? :-)

**Comment by 1peter10** [comment]
The way to solve this seems to be to bundle the missing library. This is how Fluffychat (another Flutter app) fixed it: https://github.com/flathub/im.fluffychat.Fluffychat/pull/66/commits/566270398b97db3c6c73986c5f344df8670bbc4b

**Comment by j0chn1** [comment]
Hey @1peter10,
thanks for the link. I changed my build script and published it. 
Maybe you can test this again.

**Comment by 1peter10** [comment]
Hey @j0chn1,
thanks for working on this so quickly! Sadly, it still fails with the same error (yes, I checked with flatpak info to make sure I have the correct release installed). My best guess would be that it's not in the correct place - but I know next to nothing about flatpak, so ... take this with a grain of salt!

**Comment by TingPing** [comment]
This should be version 1.7.5 just like on arm:

https://github.com/flathub/com.gitlab.j0chn.nextcloud_password_client/blob/584e6a1682d98d7202ff10aafe6b3e54cc18bf86/com.gitlab.j0chn.nextcloud_password_client.json#L19-L32

**Comment by j0chn1** [comment]
@1peter10 
I updated the flathub manifest. 
Unfortunately there is another error for me. But the app itself runs. 
Could you please check, if a transparent window appears (or even the whole app)?
Of course we need to wait for the release.
Thank you

**Comment by j0chn1** [comment]
> Hey @j0chn1, thanks for working on this so quickly! Sadly, it still fails with the same error (yes, I checked with flatpak info to make sure I have the correct release installed). My best guess would be that it's not in the correct place - but I know next to nothing about flatpak, so ... take this with a grain of salt!

Unfortunately I have no possibility to retests this. 
Could you be so kind and try it again? 
Thank you

**Comment by TingPing** [comment]
> Unfortunately I have no possibility to retests this.

You can run any arch (`qemu-aarch64-static` emulates it):

```
flatpak install --arch=aarch64 com.gitlab.j0chn.nextcloud_password_client
flatpak run --arch=aarch64 com.gitlab.j0chn.nextcloud_password_client
> /app/bin/nextcloud_password_client: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory
```

**Comment by 1peter10** [comment]
Sorry for being slow to respond, it successfully launches now :tada:
