### ISSUE TITLE
Application name contains trademarked name

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.gitlab.j0chn.nextcloud_password_client#35]
Hello we are tracking a bunch of applications with trademark violations.

The current application name contains "Nextcloud" which is someone else's brand name https://nextcloud.com/trademarks/. Additionally this application is not related to any official Nextcloud apps so using "Nextcloud Password client" is confusing.

Please try to use your name for the application to avoid trademark issues and confusing people. I think 2 months is a reasonable time period for us to wait for the name to be changed.

You can find some resources for application names in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-name

And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by bbhtt** [comment]
@j0chn1 What's the update here? The two months is coming to an end

**Comment by j0chn1** [comment]
Hello @bbhtt.
as I did the not see the message earlier this morning, I of course did not do anything regarding this.

I checked the trademarks after your claim and see this point valid for my application

`You should not include a Nextcloud mark in the name of your application, product or service, regardless of whether it is commercial or non-commercial in nature. This includes online services, such as e-commerce, community, blog, informational, promotional, and personal home page sites as well as Nextcloud apps, client apps or third party apps which interact with Nextcloud.

With that said, we consider it permissible to use an Nextcloud mark in a file, folder, directory, or path name. **We also recognize that the Nextcloud Community needs some way to identify projects, products, and services that are compatible with Nextcloud. This is only allowed for non-commercial purposes.**
`
As this app uses the nextcloud passwords app, I consider it related to nextcloud which makes it valid to use the name.

Nevertheless, I will contact nextcloud directly to get confirmation and think about another name and check the steps and effort needed to change it. 

So please be patient ;)

**Comment by bbhtt** [comment]
If you can get permission from them to use it; it's fine by me.

If you do please post the email etc. giving that permission here; so that we have a reference.

**Comment by j0chn1** [comment]
I will inform you as soon as I got something.

**Comment by j0chn1** [comment]
![image](https://github.com/flathub/com.gitlab.j0chn.nextcloud_password_client/assets/87828588/9dd8872f-8051-426d-bf47-a8e34e59ebac)
Here as a proof of my inquiry at nextcloud ;)

**Comment by bbhtt** [comment]
Did you get a reply from them?

**Comment by j0chn1** [comment]
Nope.
I just called them to ask for a status. 
The sercive employee told me, she would forward the mail to a responsable and he would get in touch with me.
I hope, they are doing so until end of the week.

**Comment by j0chn1** [comment]
Nextcloud forwarded the topic to their marketing department, because they are responsible for trademarks. 
They will either answer here or get in touch with my contact person who then will answer me.

**Comment by jospoortvliet** [comment]
Hi folks! I've emailed @j0chn1 permission to use our trademark for his app today! As community app, that's of course cool. Sorry that this kind of got lost in sales/support. Let me know if you need something from your side!

@j0chn1 best email me if there's something I need to do, I'm atrociously behind on github notifications 🙈

**Comment by bbhtt** [comment]
Ok thanks.
